### ISSUE TITLE
ЕСИА что-то опять поменяли?

### ISSUE THREAD

**Issue by umbruxo** [AISGorod/AISGorod.AspNetCore.Authentication.Esia#17]
Добрый день! неделю уже возникает такая ошибка при попытке авторизации через ЕСИА: Они опять что-то поменяли?

RequestID: |6a0f0dbb-4fc6471f90c83f0c. this /signin-oidc threw an exception System.Exception: An error was encountered while handling the remote login.

       ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

       ---> System.ComponentModel.Win32Exception (0x80090308): Предоставленный функции токен неправилен

         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)

         at System.Net.Security.SecureChannel.CreateFatalHandshakeAlertToken(SslPolicyErrors sslPolicyErrors, X509Chain chain)

         at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)

         at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken)

         at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)

         at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)

         at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)

         at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)

         at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)

         at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)

         at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)

         at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)

         at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)

         at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)

      --- End of stack trace from previous location where exception was thrown ---

         at System.Net.Security.SslStream.ThrowIfExceptional()

         at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)

         at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)

         at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)

         at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)

         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

      --- End of stack trace from previous location where exception was thrown ---

         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

         --- End of inner exception stack trace ---

         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

         at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)

         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()

         --- End of inner exception stack trace ---

         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()

         at AISGorod.AspNetCore.Authentication.Esia.EsiaHandler.HandleRequestAsync()

         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by vladdy-moses** [comment]
Добрый день! На новой развёртке приложения столкнулись с похожей проблемой. Решаем...
По результату сообщу здесь.

**Comment by umbruxo** [comment]
Может ли быть связано с использованием самоподписанных сертификатов при отправке запросов к есиа?

**Comment by vladdy-moses** [comment]
У нас также используются самоподписанные сертификаты.

Попробуйте зайти на сервере в браузере по адресу <https://esia.gosuslugi.ru/>.
У нас была проблема с доверенным центром сертификации. Добавили его - проблема ушла.

[Файл с сертификатом ЭП от Минкомсвязи](https://github.com/AISGorod/AISGorod.AspNetCore.Authentication.Esia/files/6389503/minsv.zip)

**Comment by umbruxo** [comment]
А как диагноситровать эту проблему с доверенным центром сертификации на мощности заказчика? Просто на их сервере открыть страницу и увидеть что? Сами госуслуги открываются на сервере, где находится разработка. Но У Заказчика настроена переадресация, т.е. наружу этот ресурс высунут не на прямую, а через еще один сервер.

**Comment by vladdy-moses** [comment]
Попробуйте на сервере заказчика сделать следующее:
1) В Internet Explorer зайти на https://esia.gosuslugi.ru
2) Убедиться, что после предупреждений наподобие "Вы пытаетесь зайти на защищённый сайт" веб-сайт откроется, т.е. не выйдет страница-заглушка с указанием на ошибку в сертификате. У нас в IE 11 отображается бесконечный spinner, но сам сайт открылся, соединение установилось.
3) Проверьте, что сертификат является подтверждённым. Для этого около адресной строки есть символ замка, во всплывающем окне "Просмотр сертификатов". В открывшимся окне не должно быть проблем, в пути сертификации также должно быть всё хорошо.

Если на сервере установлен КриптоПРО (как у нас было), можно из папки `C:\Program Files\Crypto Pro\CSP` (может отличаться) от имени администратора выполнить команду `csptest.exe -tlsc -server esia.gosuslugi.ru -file favicon.ico`.
Вывод должен быть примерно таким:
```
DContext expired: OK if file is completely downloaded
Reply status: HTTP/1.1 200 OK
1 connections, 599 bytes in 0.204 seconds;
Total: SYS: 0,125 sec USR: 0,031 sec UTC: 0,265 sec
[ErrorCode: 0x00000000]
```

Переадресация может быть проблемой, да. Если используется прокси-сервер, можно его настроить в Backchannel в настройках подключения к ЕСИА.

**Comment by Alex-Alimerzaev** [comment]
Дорого  дня!
А как вы самоподписный сертификат загрузили в ЕСИА?

Мы сейчас пытались такое сделать и технологический портал отправлял нас подальше.
Пытались туда загрузить RSA сертификат и получили в ответ что сертификат не соответствует разрешенному перечню стандартов. Из разрешенных только ГОСТ 3410 

А при попытке загрузить ГОСТ 3410 сертификат (по вашим интсрукциям через wsl openssl сгенерированный) получили сообщение что сертификат не прошел проверку действительности. Обратитесь в удостоверяющий центр.

Даже тестовый стенд не настроили.

**Comment by planar74** [comment]
Сталкивался с проблемой. Вылечить удалось только добавив 
options.TokenValidationParameters.ValidateIssuer = false;
в функции BuildAction<TEsiaEvents>() класса OpenIdConnectOptionsBuilder

**Comment by umbruxo** [comment]
Ничего не сработало не знаю, что делать(

**Comment by umbruxo** [comment]
Убрали переадресацию, теперь ходим к есиа напрямую с машины, где стоит приложение, но ошибка осталась 
 Error RequestID: |89d5d7c4-4d8c3b6c7e75e2f0. this /signin-oidc threw an exception System.Exception: An error was encountered while handling the remote login.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090308): Предоставленный функции токен неправилен

Что поделать понять не могу из-за чего

**Comment by umbruxo** [comment]
Все, закрываю. Добавил сертификат минкомсвязи в доверенные и тоже помогло.
