### ISSUE TITLE
Correlation failed

### ISSUE THREAD

**Issue by SkyLimited** [AISGorod/AISGorod.AspNetCore.Authentication.Esia#18]
Добрый день.

Запускаю демонстрационный пример, все проходит хорошо, до момента возврата на сайт с госуслуг,
http://localhost:5000/signin-oidc?code=eyJ2ZXIiO.......

В этом месте падает с ошибкой Correlation failed.
`warn: AISGorod.AspNetCore.Authentication.Esia.EsiaHandler[15]
      '.AspNetCore.Correlation.Esia.DOqICFYAzSI14n-ZGo1lKwogH84ymSrIWbyg88T_80Q' cookie not found.
info: AISGorod.AspNetCore.Authentication.Esia.EsiaHandler[4]
      Error from RemoteAuthentication: Correlation failed..
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM8RCJC6MK0D", Request id "0HM8RCJC6MK0D:00000004": An unhandled exception was thrown by the application.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at AISGorod.AspNetCore.Authentication.Esia.EsiaHandler.HandleRequestAsync() in E:\WRK\112lo.ru\ESIA_Test\src\EsiaHandler.cs:line 46
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 49.3719ms 500`

Гугление не привело к понимаю проблемы, прошу помощи.

**Comment by SkyLimited** [comment]
upd: Проблема проявляется только в Chrome-подобных браузерах, и лечится выставлением 
` app.UseCookiePolicy(new CookiePolicyOptions()
            {
                MinimumSameSitePolicy = SameSiteMode.Lax
            });
`
